### PR TITLE
.travis.yml: Run the p_group_homology testsuite

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by simon-king-jena** [comment]
Hi! Previously I didn't dare to run the test suite, because I thought it would exceed the permitted time on travis. But apparently running the tests basically does work! AFAIC, there is only one failing test, but the same test appears in several locations. So, I will merge your pull request, pull it locally to my machine, make it so that the tests will work, and push back.

By the way, now that Sage is about to drop python-2 support, I think the tests should be python-3 only.

Best regards,
Simon

**Comment by simon-king-jena** [comment]
Matthias, it seems that the branch that I work with isn't "master", but is the branch "travis". Actually I don't recall whether I had reasons to create the "travis" branch in the first place. Also, my local work branch is pushing to "travis", not to "master".

Perhaps the reason was that "master" should be more or less stable, whereas "travis" is supposed to be for development (it is called "travis" and not "develop", as the whole repository was created only in order to be able to do travis-ci), and I would push from "travis" to "master" only when there is a new release --- in other words, "master" isn't a good location for pull requests, IMHO.

So, I'm now trying to pull your pull request over to "travis".

**Comment by simon-king-jena** [comment]
I am still not at ease with git nor with github. Can you please help by answering the following questions:
- How can I make it so that your pull request is merged into the travis branch on github?
- How can I revert the master branch on github to the latest release (i.e., to the commit before the merge request)?

**Comment by simon-king-jena** [comment]
Sorry that I didn't wait for your answer. I pulled the old github master to my local machine, moved the commit from your pull request to my local travis branch, reverted my local master branch to its previous state (i.e., to tag v3.3), pushed my local travis to github travis and force-pushed my local master to github master.

So, from my perspective, the branches are now where they should be. Nonetheless, please tell me how I can merge a pull request to travis instead of master. I had the same problem with the pull request from Frédéric Chapoton, and I should finally learn how to work with pull requests.

**Comment by mkoeppe** [comment]
Hi Simon,
On Sat, Jan 4, 2020 at 4:47 PM Simon King <notifications@github.com> wrote:

> please tell me how I can merge a pull request to travis instead of master.
> I had the same problem with the pull request from Frédéric Chapoton, and I
> should finally learn how to work with pull requests.
>

When you receive a pull request on GitHub, you can edit its "base
branch" to merge into. See here:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request


A different workflow goes through your local machine. You add my fork of
your repository using `git remote add mkoeppe
https://github.com/mkoeppe/p_group_cohomology.git`, fetch the branches from
it with `git fetch mkoeppe` and then you can merge from my branches using
`git merge mkoeppe/master` and so on.

**Comment by simon-king-jena** [comment]
Hi Matthias!

> When you receive a pull request on GitHub, you can edit its "base branch" to merge into.

Thank you! By the way, with the latest commits on the "travis" branch, all tests pass. So, probably it is time for a version 3.3.1.

Best regards,
Simon

**Pull request merged**
