### PR TITLE
better any

### PR DESCRIPTION
**Pull request by fchapoton**
without list creation

### CODE REVIEW

**Comment by simon-king-jena** [comment]
Hi Frédéric, thank you for the patch. I think it is clear that I should merge it.
It is the first time that I do actual work on github, so, I hope I get it right. I click on "merge pull request", and then in the repository on my laptop I do "git pull", correct?

**Comment by fchapoton** [comment]
yes, exactly. click on Merge here, and refresh you local clone by "git pull"

**Comment by simon-king-jena** [comment]
"git pull" didn't give me your change. "git log" still shows the old head.

**Comment by fchapoton** [comment]
then use "git pull origin master"
First check using git log that your local branch is following the remote "master"

**Comment by simon-king-jena** [comment]
OK, I see the problem: My local repository (and the package included in Sage!) is at version 3.3, the github repository is at version 3.2.

So, I should rather push my local repository, AFTER reverting the pull request, and then one can improve the use of "any" again. Problem: I don't know how to revert merging the pull request.

**Comment by fchapoton** [comment]
you can force push (but be careful)
"git push -f origin HEAD:master"

**Comment by simon-king-jena** [comment]
Do I need to specify origin HEAD:master? Or would "git push -f" suffice, as the remote branch is associated with the local branch?

**Comment by simon-king-jena** [comment]
"git push -f" said that everythin is up to date. But "git push -f origin HEAD:master" did something. I hope it did well...

**Comment by simon-king-jena** [comment]
Hi Frédéric, I have created a commit that corresponds to your pull request. So, I guess the issue is solved now.

I only wonder why I don't receive notification by travis-ci. Previously, when pushing any change, travis-ci did automatic tests. Is there any reason why this has changed?

**Pull request merged**
